"""
This type stub file was generated by pyright.
"""

"""A simple demonstration of the `coloredlogs` package."""
logger = ...
DEMO_DELAY = ...

def demonstrate_colored_logging():  # -> None:
    """Interactively demonstrate the :mod:`coloredlogs` package."""
    ...
